/* eslint-disable */

// @ts-nocheck

// This file is auto-generated by @renr/parcel-reporter-rsc-router.
// Do not edit it manually.
// You should also exclude it from your linting/formatting rules.

import type { RouteData, RouteNode } from "@renr/parcel-rsc-router";

declare module "@renr/parcel-rsc-router" {
  namespace App {
    interface Routes {
      "/": { slug: "index"; rsc: "/index.rsc"; html: "/index.html" };
      "/about": { slug: "about"; rsc: "/about.rsc"; html: "/about.html" };
      "/blog/index": {
        slug: "index";
        rsc: "/blog/index.rsc";
        html: "/blog/index.html";
      };
      "/blog/test_2024-10-31": {
        slug: "test_2024-10-31";
        rsc: "/blog/test_2024-10-31.rsc";
        html: "/blog/test_2024-10-31.html";
      };
    }
  }
}

export const routes: RouteData[] = [
  {
    path: "/",
    slug: "index",
    rsc: "/index.rsc",
    html: "/index.html",
  },
  {
    path: "/about",
    slug: "about",
    rsc: "/about.rsc",
    html: "/about.html",
  },
  {
    path: "/blog/index",
    slug: "index",
    rsc: "/blog/index.rsc",
    html: "/blog/index.html",
  },
  {
    path: "/blog/test_2024-10-31",
    slug: "test_2024-10-31",
    rsc: "/blog/test_2024-10-31.rsc",
    html: "/blog/test_2024-10-31.html",
  },
];

export const routeTree: RouteNode = {
  path: "/",
  slug: "index",
  html: "/index.html",
  rsc: "/index.rsc",
  children: [
    {
      path: "/about",
      slug: "about",
      html: "/about.html",
      rsc: "/about.rsc",
      children: [],
    },
    {
      path: "/blog/index",
      slug: "index",
      html: "/blog/index.html",
      rsc: "/blog/index.rsc",
      children: [
        {
          path: "/blog/test_2024-10-31",
          slug: "test_2024-10-31",
          html: "/blog/test_2024-10-31.html",
          rsc: "/blog/test_2024-10-31.rsc",
          children: [],
        },
      ],
    },
  ],
};

// lookup routes by PageProps url
export const routesByPage: Record<string, RouteData> = {
  "/index.html": {
    path: "/",
    slug: "index",
    rsc: "/index.rsc",
    html: "/index.html",
  },
  "/about.html": {
    path: "/about",
    slug: "about",
    rsc: "/about.rsc",
    html: "/about.html",
  },
  "/blog/index.html": {
    path: "/blog/index",
    slug: "index",
    rsc: "/blog/index.rsc",
    html: "/blog/index.html",
  },
  "/blog/test_2024-10-31.html": {
    path: "/blog/test_2024-10-31",
    slug: "test_2024-10-31",
    rsc: "/blog/test_2024-10-31.rsc",
    html: "/blog/test_2024-10-31.html",
  },
};
