/* eslint-disable */

// This file is auto-generated by @renr/parcel-reporter-rsc-router.
// Do not edit it manually.
// You should also exclude it from your linting/formatting rules.

import type { App, RouteData, RouteNode } from "@renr/parcel-rsc-router";

declare module "@renr/parcel-rsc-router" {
  namespace App {
    interface Routes {
      "/": { slug: "root"; path: "/"; rsc: "/root.rsc"; html: "/root.html" };
      "/about": {
        slug: "about";
        path: "/about";
        rsc: "/about.rsc";
        html: "/about.html";
      };
      "/blog": {
        slug: "blog";
        path: "/blog";
        rsc: "/blog/index.rsc";
        html: "/blog/index.html";
      };
      "/blog/test_2024-10-31": {
        slug: "test_2024-10-31";
        path: "/blog/test_2024-10-31";
        rsc: "/blog/test_2024-10-31.rsc";
        html: "/blog/test_2024-10-31.html";
      };
    }
  }
}

export const flatRoutes = [
  {
    path: "/",
    slug: "root",
    rsc: "/root.rsc",
    html: "/root.html",
  },
  {
    path: "/about",
    slug: "about",
    rsc: "/about.rsc",
    html: "/about.html",
  },
  {
    path: "/blog",
    slug: "blog",
    rsc: "/blog/index.rsc",
    html: "/blog/index.html",
  },
  {
    path: "/blog/test_2024-10-31",
    slug: "test_2024-10-31",
    rsc: "/blog/test_2024-10-31.rsc",
    html: "/blog/test_2024-10-31.html",
  },
] as const satisfies RouteData[];

export const routeTree = {
  path: "/",
  slug: "root",
  html: "/root.html",
  rsc: "/root.rsc",
  children: [
    {
      path: "/about",
      slug: "about",
      html: "/about.html",
      rsc: "/about.rsc",
      children: [],
    },
    {
      path: "/blog",
      slug: "blog",
      html: "/blog/index.html",
      rsc: "/blog/index.rsc",
      children: [
        {
          path: "/blog/test_2024-10-31",
          slug: "test_2024-10-31",
          html: "/blog/test_2024-10-31.html",
          rsc: "/blog/test_2024-10-31.rsc",
          children: [],
        },
      ],
    },
  ],
} as const satisfies RouteNode;

// lookup routes by PageProps url
export const routesByPage = {
  "/root.html": {
    path: "/",
    slug: "root",
    rsc: "/root.rsc",
    html: "/root.html",
  },
  "/about.html": {
    path: "/about",
    slug: "about",
    rsc: "/about.rsc",
    html: "/about.html",
  },
  "/blog/index.html": {
    path: "/blog",
    slug: "blog",
    rsc: "/blog/index.rsc",
    html: "/blog/index.html",
  },
  "/blog/test_2024-10-31.html": {
    path: "/blog/test_2024-10-31",
    slug: "test_2024-10-31",
    rsc: "/blog/test_2024-10-31.rsc",
    html: "/blog/test_2024-10-31.html",
  },
} satisfies {
  [Key in keyof App.Routes as App.Routes[Key]["html"]]: App.Routes[Key];
};
