/* eslint-disable */

// This file is auto-generated by @renr/parcel-reporter-rsc-router.
// Do not edit it manually.
// You should also exclude it from your linting/formatting rules.

import type { App, RouteData, RouteNode } from "@renr/parcel-rsc-router";

declare module "@renr/parcel-rsc-router" {
  namespace App {
    interface Routes {
      "/": { slug: "index"; path: "/"; rsc: "/index.rsc"; html: "/index.html" };
      "/blog": {
        slug: "blog";
        path: "/blog";
        rsc: "/blog/index.rsc";
        html: "/blog/index.html";
      };
      "/blog/test_2024-10-31": {
        slug: "test_2024-10-31";
        path: "/blog/test_2024-10-31";
        rsc: "/blog/test_2024-10-31.rsc";
        html: "/blog/test_2024-10-31.html";
      };
      "/mdx-page": {
        slug: "mdx-page";
        path: "/mdx-page";
        rsc: "/mdx-page.rsc";
        html: "/mdx-page.html";
      };
    }
  }
}

export const flatRoutes = [
  {
    path: "/",
    slug: "index",
    rsc: "/index.rsc",
    html: "/index.html",
  },
  {
    path: "/blog",
    slug: "blog",
    rsc: "/blog/index.rsc",
    html: "/blog/index.html",
  },
  {
    path: "/blog/test_2024-10-31",
    slug: "test_2024-10-31",
    rsc: "/blog/test_2024-10-31.rsc",
    html: "/blog/test_2024-10-31.html",
  },
  {
    path: "/mdx-page",
    slug: "mdx-page",
    rsc: "/mdx-page.rsc",
    html: "/mdx-page.html",
  },
] as const satisfies RouteData[];

export const routeTree = {
  path: "/",
  slug: "index",
  html: "/index.html",
  rsc: "/index.rsc",
  children: [
    {
      path: "/blog",
      slug: "blog",
      html: "/blog/index.html",
      rsc: "/blog/index.rsc",
      children: [
        {
          path: "/blog/test_2024-10-31",
          slug: "test_2024-10-31",
          html: "/blog/test_2024-10-31.html",
          rsc: "/blog/test_2024-10-31.rsc",
          children: [],
        },
      ],
    },
    {
      path: "/mdx-page",
      slug: "mdx-page",
      html: "/mdx-page.html",
      rsc: "/mdx-page.rsc",
      children: [],
    },
  ],
} as const satisfies RouteNode;

// lookup routes by PageProps url
export const routesByPage = {
  "/index.html": {
    path: "/",
    slug: "index",
    rsc: "/index.rsc",
    html: "/index.html",
  },
  "/blog/index.html": {
    path: "/blog",
    slug: "blog",
    rsc: "/blog/index.rsc",
    html: "/blog/index.html",
  },
  "/blog/test_2024-10-31.html": {
    path: "/blog/test_2024-10-31",
    slug: "test_2024-10-31",
    rsc: "/blog/test_2024-10-31.rsc",
    html: "/blog/test_2024-10-31.html",
  },
  "/mdx-page.html": {
    path: "/mdx-page",
    slug: "mdx-page",
    rsc: "/mdx-page.rsc",
    html: "/mdx-page.html",
  },
} satisfies {
  [Key in keyof App.Routes as App.Routes[Key]["html"]]: App.Routes[Key];
};
