/* eslint-disable */

// This file is auto-generated by @renr/parcel-reporter-rsc-router.
// Do not edit it manually.
// You should also exclude it from your linting/formatting rules.

import type { App, RouteData, RouteNode } from "@renr/parcel-rsc-router";

declare module "@renr/parcel-rsc-router" {
  namespace App {
    interface Routes {
      "/": { slug: "index"; path: "/"; rsc: "/index.rsc"; html: "/index.html" };
      "/mdx": { slug: "mdx"; path: "/mdx"; rsc: "/mdx.rsc"; html: "/mdx.html" };
    }
  }
}

export const flatRoutes = [
  {
    path: "/",
    slug: "index",
    rsc: "/index.rsc",
    html: "/index.html",
  },
  {
    path: "/mdx",
    slug: "mdx",
    rsc: "/mdx.rsc",
    html: "/mdx.html",
  },
] as const satisfies RouteData[];

export const routeTree = {
  path: "/",
  slug: "index",
  html: "/index.html",
  rsc: "/index.rsc",
  children: [
    {
      path: "/mdx",
      slug: "mdx",
      html: "/mdx.html",
      rsc: "/mdx.rsc",
      children: [],
    },
  ],
} as const satisfies RouteNode;

// lookup routes by PageProps url
export const routesByPage = {
  "/index.html": {
    path: "/",
    slug: "index",
    rsc: "/index.rsc",
    html: "/index.html",
  },
  "/mdx.html": {
    path: "/mdx",
    slug: "mdx",
    rsc: "/mdx.rsc",
    html: "/mdx.html",
  },
} satisfies {
  [Key in keyof App.Routes as App.Routes[Key]["html"]]: App.Routes[Key];
};
