name: CI

on:
  push:
    branches:
      - "**"

jobs:
  build-lint-format-test:
    name: Type Check, Format and Lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.13.1

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: install dependencies
        run: pnpm install

      - name: build packages
        run: pnpm build

      - name: type Check
        run: pnpm type-check

      - name: format
        run: pnpm format:ci

      - name: lint
        run: pnpm lint:ci

      - name: test
        run: pnpm test:ci
